<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="Vicky" failures="1" tests="1" name="Default test" time="117.237" errors="0" timestamp="2020-10-08T15:15:35 IST">
  <testcase classname="wave.test.cases.TestSuite" name="WAVE_TC_02" time="55.873">
    <failure type="java.io.IOException" message="Bad pathname">
      <![CDATA[java.io.IOException: Bad pathname
at java.base/java.io.WinNTFileSystem.canonicalize0(Native Method)
at java.base/java.io.WinNTFileSystem.canonicalize(WinNTFileSystem.java:415)
at java.base/java.io.File.getCanonicalPath(File.java:621)
at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:785)
at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:747)
at Generic.pack.GenericType.captureScreenShot(GenericType.java:419)
at Generic.pack.GenericType.softAssert(GenericType.java:399)
at step.base.pack.StepBase.MainLooper(StepBase.java:113)
at step.base.pack.StepBase.Step(StepBase.java:40)
at Specifics.pack.SpecificType.login(SpecificType.java:98)
at step.base.pack.StepBase.MainLooper(StepBase.java:122)
at step.base.pack.StepBase.keyword(StepBase.java:50)
at wave.test.cases.TestSuite.WAVE_TC_02(TestSuite.java:71)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- WAVE_TC_02 -->
  <testcase classname="wave.test.cases.TestSuite" name="WAVE_TC_01" time="0.0">
    <ignored/>
  </testcase> <!-- WAVE_TC_01 -->
</testsuite> <!-- Default test -->
